### ISSUE TITLE
Would like a way to list environments

### ISSUE THREAD

**Issue by robeberhardt** [oursiberia/ssmenv#8]
`ssmenv env:list` or something

**Comment by bryanjswift** [comment]
The things referred to as `STAGE` in the CLI examples?

**Comment by robeberhardt** [comment]
yeah, I come back to a project after a month of not looking at it and I don't know whether I called my environments 'dev' or 'development' or 'local' or whatever

**Comment by bryanjswift** [comment]
Yep an `env:list` command would be helpful.

I want to make `STAGE` optional (or multiple flag actually). If it isn't set then it puts the value in all environments, if it is set then it only puts it into the specified ones.

**Comment by robeberhardt** [comment]
optional sounds good

**Comment by bryanjswift** [comment]
`env:list` command added in [v0.3.0](https://github.com/oursiberia/ssmenv/releases/tag/v0.3.0)
